function Hd = txrxLpfRC
%TXRXLPFRC Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.1 and the Signal Processing Toolbox 6.19.
% Generated on: 11-Nov-2013 02:23:40

% FIR Window Raised-cosine filter designed using the FIRRCOS function.

% All frequency values are in Hz.
Fs = 44100;  % Sampling Frequency

N    = 100;        % Order
Fc   = 441;        % Cutoff Frequency
TM   = 'Rolloff';  % Transition Mode
R    = 0.2;        % Rolloff
DT   = 'sqrt';     % Design Type
Beta = 0.3;        % Window Parameter

% Create the window vector for the design algorithm.
win = kaiser(N+1, Beta);

% Calculate the coefficients using the FIR1 function.
b  = firrcos(N, Fc/(Fs/2), R, 2, TM, DT, [], win);
Hd = dfilt.dffir(b);

% [EOF]
