function Hd = bpfchev19k21k250
%BPFCHEV19K21K250 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.1 and the Signal Processing Toolbox 6.19.
% Generated on: 18-Mar-2014 20:59:11

% FIR Window Bandpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 44100;  % Sampling Frequency

N             = 250;      % Order
Fc1           = 19000;    % First Cutoff Frequency
Fc2           = 21000;    % Second Cutoff Frequency
flag          = 'scale';  % Sampling Flag
SidelobeAtten = 60;       % Window Parameter
% Create the window vector for the design algorithm.
win = chebwin(N+1, SidelobeAtten);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, [Fc1 Fc2]/(Fs/2), 'bandpass', win, flag);
Hd = dfilt.dffir(b);

% [EOF]
