function Hd = txBpf20k
%TXBPF20K Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.1 and the Signal Processing Toolbox 6.19.
% Generated on: 02-Sep-2013 23:42:32

% FIR Window Bandpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 44100;  % Sampling Frequency

Fstop1 = 19000;             % First Stopband Frequency
Fpass1 = 19500;             % First Passband Frequency
Fpass2 = 20500;             % Second Passband Frequency
Fstop2 = 21000;             % Second Stopband Frequency
Dstop1 = 3.1622776602e-08;  % First Stopband Attenuation
Dpass  = 0.057501127785;    % Passband Ripple
Dstop2 = 3.1622776602e-08;  % Second Stopband Attenuation
flag   = 'scale';           % Sampling Flag

% Calculate the order from the parameters using KAISERORD.
[N,Wn,BETA,TYPE] = kaiserord([Fstop1 Fpass1 Fpass2 Fstop2]/(Fs/2), [0 ...
                             1 0], [Dstop1 Dpass Dstop2]);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Wn, TYPE, kaiser(N+1, BETA), flag);
Hd = dfilt.dffir(b);

% [EOF]
